### ISSUE TITLE
"R session aborted" when using gofN()

### ISSUE THREAD

**Issue by liluqi1991** [statnet/ergm.multi#30]
Hello, I have been using ergm.multi in my manuscript and a reviewer has requested a diagnostic analysis. However, **whenever I employ _**Layer()**_ to define a multilayer network, the “R Session Aborted” error occurs after executing **_gofN()_**.**
I have noticed that in Krivitsky’s study (2020, https://doi.org/10.1007/s11336-020-09720-7), the goodness-of-fit assessment for the Lazega example was successfully conducted, and it is likely that the model was specified using Layer().
I would greatly appreciate any assistance in solving this issue.

```r
library(ergm.multi)
data(florentine)

# Work:
flo <- Networks(m = flomarriage, b = flobusiness)
fit <- ergm(flo~N(~edges))
gof<-gofN(fit)


# Not work (R session aborted):
flo <- Layer(m = flomarriage, b = flobusiness)
fit <- ergm(flo ~ L(~edges, ~m)+L(~edges, ~b))
gof<-gofN(fit)
``` 

![image](https://github.com/statnet/ergm.multi/assets/69191187/c6a88a98-a1c4-4e7c-aa20-8b805923157d)

**Comment by krivit** [comment]
`gofN()` is for samples of networks. It doesn't work for multilayer models, nor should it, since layers are generally not independent. Diagnostics for multilayer models are on the roadmap, but it'll be a while yet.

**Comment by krivit** [comment]
To add to this, the diagnostics for the paper were done using bespoke code, and I haven't had a chance to make it general.

**Comment by krivit** [comment]
And thank you, @liluqi1991, for flagging this issue.

**Comment by liluqi1991** [comment]
> And thank you, @liluqi1991, for flagging this issue.

Thank you very much for your reply.
