### ISSUE TITLE
@ZiVa06m reference does not compile correctly 

### ISSUE THREAD

**Issue by drh20drh20** [statnet/ergm.multi#8]
In ergm.multi-package.R, the @ZiVa06m citation does not correctly show up in the help docs and I can't see why

**Comment by krivit** [comment]
Long story short: `Rdtools` takes an `@` at the start of `\insertCite{}{}` argument to mean that what's to follow is text with citations embedded, and eats the `@`, and I think `Roxygen` also gives it a special meaning and eats it. To make it propagate, I had to write `\insertCite{@@@Zi...`.
